### ISSUE TITLE
Simplification of website

### ISSUE THREAD

**Issue by ghost** [Cleop/waves-within#3]
![Waves_within_Updated](https://user-images.githubusercontent.com/7489492/81802304-b743aa80-950d-11ea-8618-d1a08f4032ac.png)

Text is as follows

<Homepage>
Hello, I'm Anish,
I enjoy building products that aim to solve real life problems and have built them at Facebook, Farewill, JustGiving and more.
I also find therapy in writing honestly about notable life experiences and extracting the key learnings from them, you can read these short articles below. 
If you want to talk to me, please get in touch.
Thanks for your time.
<Homepage Links>
Facebook - https://newsroom.fb.com/news/2018/11/inside-feed-community-integrity-keeping-people-safe/
Farewill - https://www.farewill.com
JustGiving - https://www.justgiving.com/crowdfunding
more - https://uk.linkedin.com/in/dbkho

**Comment by Cleop** [comment]
Reviewed by @mcgi5ah5 ✅
